// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAeTKRoZe21GoSL0FiVAbggqfhTdeB90s',
    appId: '1:1036716919728:web:218141f30a262413a4a475',
    messagingSenderId: '1036716919728',
    projectId: 'fir-auth-b5358',
    authDomain: 'fir-auth-b5358.firebaseapp.com',
    storageBucket: 'fir-auth-b5358.firebasestorage.app',
    measurementId: 'G-JFPSSJ0XC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKzw7b_2Ay6oDotElslBnmt5RJj5FedA',
    appId: '1:1036716919728:android:c7ff063e42829539a4a475',
    messagingSenderId: '1036716919728',
    projectId: 'fir-auth-b5358',
    storageBucket: 'fir-auth-b5358.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqOOi_cX1a__OtZlkXXdM_X0yxnnxHvwU',
    appId: '1:1036716919728:ios:058e7028fd0b9bb8a4a475',
    messagingSenderId: '1036716919728',
    projectId: 'fir-auth-b5358',
    storageBucket: 'fir-auth-b5358.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqOOi_cX1a__OtZlkXXdM_X0yxnnxHvwU',
    appId: '1:1036716919728:ios:058e7028fd0b9bb8a4a475',
    messagingSenderId: '1036716919728',
    projectId: 'fir-auth-b5358',
    storageBucket: 'fir-auth-b5358.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAeTKRoZe21GoSL0FiVAbggqfhTdeB90s',
    appId: '1:1036716919728:web:854275564b3dac18a4a475',
    messagingSenderId: '1036716919728',
    projectId: 'fir-auth-b5358',
    authDomain: 'fir-auth-b5358.firebaseapp.com',
    storageBucket: 'fir-auth-b5358.firebasestorage.app',
    measurementId: 'G-RK13XX3E6B',
  );
}
